### ISSUE TITLE
Proyectos. Menus

### ISSUE THREAD

**Issue by ISCLuisRamirez** [ISCLuisRamirez/WebMMPI#37]
Igualar los menus de proyectos a las divisiones existentes
![image](https://user-images.githubusercontent.com/44370473/92684462-20d89780-f2fb-11ea-8ca5-285d1b02db7d.png)

**Comment by erickavila151** [comment]
@ISCLuisRamirez 
![image](https://user-images.githubusercontent.com/69064746/92857770-cd2d8300-f3ba-11ea-88c4-de7657f5b0a5.png)
