### ISSUE TITLE
Test “responsive” vista en un iPhone 8 normal

### ISSUE THREAD

**Issue by EdgonMMPI** [ISCLuisRamirez/WebMMPI#39]
![image](https://user-images.githubusercontent.com/70658429/92684572-6006e880-f2fb-11ea-9f74-ee47a478f68a.jpeg)

**Comment by ISCLuisRamirez** [comment]
@erickavila151  hay que usar scripts de ntra. sra. de gpe. para ocultar numero de teléfono en Dispositivos Móviles (solo muestre icono de whatsapp). 

Mostrar un logotipo mas pequeño en DM

Texto dinámico mas pequeño por DM.

Cintilla gris acomodar para DM.

**Comment by erickavila151** [comment]
@ISCLuisRamirez falta corregir la cintilla 
![image](https://user-images.githubusercontent.com/69064746/93305344-fd629080-f7c3-11ea-8752-82b0cc0a165d.png)

**Comment by erickavila151** [comment]
@ISCLuisRamirez 
![image](https://user-images.githubusercontent.com/69064746/93380384-c8d2f100-f824-11ea-8a32-a9a014261b9e.png)
