### ISSUE TITLE
S1/ BODY; frase pasión por ...

### ISSUE THREAD

**Issue by EdgonMMPI** [ISCLuisRamirez/WebMMPI#40]
En la frase:

pasión por ... INVENTAR

a) el tamaño de la letra debe ser igual al que dice DIVISIONES Y SERVICIOS

b) el verbo que identifica cada "División" va siempre en mayúsculas y debe flashear en movimiento ascendente (tipo tómbola).

c) en color se queda el azul de enmedio (+ VIVO).

**Comment by ISCLuisRamirez** [comment]
@erickavila151 Encárgate de los incisos A y B, 

El C yo lo hago

**Comment by erickavila151** [comment]
@ISCLuisRamirez 
![image](https://user-images.githubusercontent.com/69064746/93422262-02354c00-f879-11ea-9eda-3d91ce382b7c.png)
