### ISSUE TITLE
S1/ BODY; en cintilla fija

### ISSUE THREAD

**Issue by EdgonMMPI** [ISCLuisRamirez/WebMMPI#41]
En la "cintilla fija" en GRIS se debe agregar un TÍTULO justificado a la izquierda, que diga:

Atendemos Sector:

- ESCOLAR
- COMERCIAL
- HOGAR
- INDUSTRIAL
- OFICINA

**Comment by ISCLuisRamirez** [comment]
@EdgonMMPI 

![image](https://user-images.githubusercontent.com/44370473/93407927-f46fce80-f858-11ea-9473-cfbb77a7aa2a.png)
