### ISSUE TITLE
S2/BODY; titulo DIVISIONES

### ISSUE THREAD

**Issue by EdgonMMPI** [ISCLuisRamirez/WebMMPI#42]
El título dice:
DIVISIONES Y SERVICIOS
    Tenemos todo lo que buscas

Debe decir:
DIVISIONES

**Comment by erickavila151** [comment]
@ISCLuisRamirez  
![image](https://user-images.githubusercontent.com/69064746/93388138-e194d400-f82f-11ea-95a4-c610a7e95d28.png)
