### ISSUE TITLE
S2/BODY; icono Adekua

### ISSUE THREAD

**Issue by EdgonMMPI** [ISCLuisRamirez/WebMMPI#43]
Logo ADEKUA

a) A la casita agregarle una regla

 ![image](https://user-images.githubusercontent.com/70658429/92688742-7e70e200-f303-11ea-9e93-af9512af7714.jpeg)

b) Dice: 
AMPLIACIÓN, REMODELACIÓN ...

   Debe decir:
ADECUAMOS TU ESPACIO

**Comment by ISCLuisRamirez** [comment]
@EdgonMMPI no tenemos ningun icono con ese detalle, si gustas puedes revisar los iconos que tomamos desde este link https://fontawesome.com/
