### ISSUE TITLE
S2/BODY icono Better

### ISSUE THREAD

**Issue by EdgonMMPI** [ISCLuisRamirez/WebMMPI#44]
Icono Better Market

a) Agregar dos llantas bajo la gráfica para que simule "carrito" de e-commerce![image](https://user-images.githubusercontent.com/70658429/92689369-82e9ca80-f304-11ea-8eee-8f61c0e0a8a6.jpeg)

b) Dice:
Representamos ...; conoce ...
   
   Debe decir:
Representamos e impulsamos tu producto.

**Comment by ISCLuisRamirez** [comment]
@EdgonMMPI no tenemos ningun icono con ese detalle, si gustas puedes revisar los iconos que tomamos desde este link https://fontawesome.com/
