### ISSUE TITLE
S2/BODY; icono ESKEMA

### ISSUE THREAD

**Issue by EdgonMMPI** [ISCLuisRamirez/WebMMPI#45]
1) Icono debe entenderse que es un kit ...

De la siguiente imágen, cambiar el número 3 por la letra A

de tal forma que el producto 1 y 2, la llave indica que entran en la caja "A".
![image](https://user-images.githubusercontent.com/70658429/92691105-abbf8f00-f307-11ea-93d9-3be087a9273a.jpeg)

2) Dice:
Tu producto en su mejor Versión ...

   Debe decir:
ARMAMOS KITS, RE-ETIQUETADO, REEMPAQUE

**Comment by ISCLuisRamirez** [comment]
@EdgonMMPI no existe un icono similiar a llo que pides, este fue el mas cercano al tema.


![image](https://user-images.githubusercontent.com/44370473/93405879-dbb0ea00-f853-11ea-8441-d5cd8b235bf7.png)
