### ISSUE TITLE
S2/BODY; vista DIVISIONES

### ISSUE THREAD

**Issue by EdgonMMPI** [ISCLuisRamirez/WebMMPI#46]
1) Desfase en la alineación de iconos ![image](https://user-images.githubusercontent.com/70658429/92691610-6a7baf00-f308-11ea-91e6-48c7b68e5499.png)

**Comment by ISCLuisRamirez** [comment]
@EdgonMMPI 
![image](https://user-images.githubusercontent.com/44370473/93408738-eb7ffc80-f85a-11ea-8833-99a79d2da448.png)
