### ISSUE TITLE
Correcciones divisiones

### ISSUE THREAD

**Issue by ISCLuisRamirez** [ISCLuisRamirez/WebMMPI#47]
Dice: Inmueble debe decir: espacio ideal

![image](https://user-images.githubusercontent.com/44370473/93538508-e59a2200-f913-11ea-9d1b-f135401dad5e.jpeg)

Dice: paga hasta; debe decir: Siempre surtido y pagas hasta su uso!

![image](https://user-images.githubusercontent.com/44370473/93538563-095d6800-f914-11ea-98bd-e61840f806cd.jpeg)

**Comment by erickavila151** [comment]
@ISCLuisRamirez 
![image](https://user-images.githubusercontent.com/69064746/93540357-0add5f00-f919-11ea-8c5a-cf6bf52bb24d.png)
